name: quicknotion
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.1.0
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^5.9.0
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_animate_on_scroll: ^0.3.0
  flutter_bloc: ^9.1.1
  flutter_getit: ^3.0.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.12.0
  get_it: ^7.7.0
  hive: ^2.2.3
  http: ^1.6.0
  intl: ^0.18.1
  loading_indicator: ^3.1.1
  logger: ^2.6.2
  multi_dropdown: ^3.0.1
  open_filex: ^4.5.0
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.1
  syncfusion_flutter_pdfviewer: ^32.1.22
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utls/
  filename: app_images.dart
