on: 
  workflow_dispatch: 
    inputs:
      environment:
        description: "Choose env"
        required: true
        default: "staging"
        type: choice
        options:
          - staging 
          - production
  repository_dispatch:
    types:
      - incident_report 
      

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "deploying the app to ${{inputs.environment}}"
